CREATE TABLE students (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE classes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(150) NOT NULL,
    term         VARCHAR(50)  NOT NULL,
    room         VARCHAR(50),
    teacher_name VARCHAR(150) NOT NULL,
    capacity     INT          NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE enrollments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT      NOT NULL REFERENCES students(id),
    class_id    BIGINT      NOT NULL REFERENCES classes(id),
    status      VARCHAR(20) NOT NULL,
    enrolled_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (student_id, class_id)
);

CREATE TABLE attendance_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL REFERENCES students(id),
    class_id        BIGINT NOT NULL REFERENCES classes(id),
    attendance_date DATE   NOT NULL,
    status          VARCHAR(20) NOT NULL,
    UNIQUE (student_id, class_id, attendance_date)
);

CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email VARCHAR(255) NOT NULL,
    subject         VARCHAR(255) NOT NULL,
    body            VARCHAR(2000) NOT NULL,
    type            VARCHAR(50)  NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_enrollments_student ON enrollments(student_id);
CREATE INDEX idx_enrollments_class ON enrollments(class_id);
CREATE INDEX idx_attendance_class_date ON attendance_records(class_id, attendance_date);
