apiVersion: v1
kind: Service
metadata:
  name: campusflow-monolith
  namespace: campusflow
  labels:
    app: campusflow-monolith
spec:
  selector:
    app: campusflow-monolith
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
